import { Link, useParams, useSearchParams } from 'react-router-dom';
import Layout from '../components/Layout';
import { CatalogError, CatalogLoading } from '../components/CatalogNotice';
import { Evidence, OtherActivities, OtherDocuments, OtherStatuses, OtherYearSelect, StructuredText, OriginalCheckNote } from '../components/SchoolOtherContent';
import { schoolOtherCatalog } from '../lib/schoolOtherCatalog';
import { useSchoolOtherData } from '../lib/useSchoolOtherData';
import { otherKindLabels, otherLink, otherYear, otherLimitation, otherConflict, otherPersonRole } from '../lib/schoolOtherPresentation';
import { officialLink } from '../lib/schoolLinks';

export default function SchoolOtherProgramDetail() {
  const {id=''}=useParams(); const [params]=useSearchParams(); const year=otherYear(params.get('edition'));
  const state=useSchoolOtherData(`other-program:${id}`,retry=>schoolOtherCatalog.program(id,{retry}));
  const program=state.data?.program; const edition=program?.editions.find(item=>item.academic_year_start===year);
  const conflicts=state.data?.source_conflicts.filter(item=>item.academic_year_start===year)||[];
  const context=`${id}:${year}`;
  return <Layout catalogNotice={false} backTo={otherLink('/other-programs',year)}><div className="space-y-7">
    <header className="space-y-3"><p className="text-sm text-text">{program ? otherKindLabels[program.program_kind] : 'Altri percorsi'}{program?.master_level ? ` · ${program.master_level}° livello` : ''}{program?.department ? ` · ${program.department}` : ''}</p><h1 className="text-3xl sm:text-4xl font-semibold text-balance break-words">{program?.name || 'Scheda del percorso'}</h1></header><OtherYearSelect />
    {state.loading ? <CatalogLoading /> : state.error ? <CatalogError message={state.error} retry={state.reload} /> : !program ? <section><h2 className="text-xl font-semibold text-balance">Percorso non trovato</h2><Link to={otherLink('/other-programs',year)} className="inline-flex min-h-11 items-center underline mt-3">Torna al catalogo</Link></section> : !edition ? <section><h2 className="text-xl font-semibold text-balance">Anno non disponibile</h2><p className="text-sm text-text mt-2">Scegli uno degli anni verificati. Non mostriamo dati di un altro anno al posto di quello richiesto.</p></section> : <>
      <section className="rounded-xl bg-card-base border border-outline-variant p-5 space-y-4"><h2 className="font-semibold text-balance">Fonti per l’anno {edition.academic_year}</h2><OtherStatuses admissions={edition.admissions_status} teaching={edition.teaching_status} />{edition.running_edition && <p className="text-sm">Edizione effettivamente in svolgimento: <strong>{edition.running_edition}</strong>. L’anno delle fonti non identifica un nuovo ingresso.</p>}</section>
      {edition.limitations.length>0 && <section className="space-y-3"><h2 className="text-xl font-semibold text-balance">Informazioni non disponibili o da interpretare</h2><p className="text-sm text-text">Le fonti ufficiali non consentono di confermare tutti i dettagli per questo anno.</p><ul className="list-disc pl-5 space-y-2 text-sm text-text break-words">{edition.limitations.map((item,i)=><li key={i}><p>{otherLimitation(item.kind)}</p><OriginalCheckNote text={item.reason} /></li>)}</ul></section>}
      {conflicts.length>0 && <section className="border border-ink rounded-xl p-5 space-y-3"><h2 className="text-xl font-semibold text-balance">Discrepanze nelle fonti ufficiali</h2>{conflicts.map(conflict=><div key={conflict.id} className="text-sm space-y-2"><p>{otherConflict(conflict.id)}</p><OriginalCheckNote text={conflict.description} />{officialLink(conflict.source_url) && <a href={officialLink(conflict.source_url)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center underline">Consulta la fonte della discrepanza<span className="sr-only"> (nuova scheda)</span></a>}</div>)}</section>}
      <section className="space-y-4"><h2 className="text-2xl font-semibold text-balance">Attività documentate</h2><p className="text-sm text-text text-pretty">I nomi dei docenti sono riportati come compaiono nelle fonti. Le attività di questi percorsi non prevedono recensioni o un calcolo del completamento del piano.</p>{edition.activities.length ? <OtherActivities activities={edition.activities} context={context} /> : <p className="rounded-xl border border-outline-variant p-4 text-sm text-text">Nessuna attività individuale pubblicata o ricostruibile nelle fonti verificate per questo anno. Consulta gli eventuali indirizzi, calendari e documenti qui sotto.</p>}</section>
      {!!edition.tracks?.length && <section className="space-y-4"><h2 className="text-2xl font-semibold text-balance">Indirizzi e percorsi formativi</h2>{edition.tracks.map((track,i)=><details key={`${context}:${track.id}:${i}`} className="rounded-xl border border-outline-variant p-4"><summary className="cursor-pointer min-h-11 text-sm font-semibold text-pretty">{[track.name,track.competition_class,track.path].filter(Boolean).join(' · ') || `Percorso ${i+1}`}<span className="block font-normal text-text mt-1 tabular-nums">{track.activities.length} attività · {track.expected_path_credits} CFU previsti{track.edition ? ` · edizione ${track.edition}` : ''}</span></summary><div className="mt-4 space-y-4"><p className="text-sm text-text tabular-nums">Somma delle attività riportate: {track.credit_total} CFU. {track.credit_check_status==='source_conflict' ? 'Il totale non coincide con i crediti previsti dalla fonte: consulta la discrepanza segnalata.' : 'Il totale numerico coincide con i crediti previsti.'}</p><OtherActivities activities={track.activities} context={`${context}:${track.id}`} /></div></details>)}</section>}
      {(['official_structured_sections','course_content_sections','curricula_raw'] as const).map((field,i)=>edition[field] && <section key={field} className="space-y-3"><h2 className="text-xl font-semibold text-balance">{['Obiettivi e struttura del percorso','Contenuti pubblicati','Curricula nelle fonti'][i]}</h2><details className="rounded-xl border border-outline-variant p-4 text-sm"><summary className="cursor-pointer min-h-11 py-3">Leggi gli estratti ufficiali</summary><StructuredText value={edition[field]} /></details></section>)}
      {!!edition.calendar_cells?.length && <section className="space-y-3"><h2 className="text-xl font-semibold text-balance">Calendario: testo originale delle tabelle</h2><p className="text-sm text-text">Le celle sono conservate nell’ordine e nella posizione della fonte. Non sono trasformate in assegnazioni a corsi o docenti quando la struttura non consente un’interpretazione certa.</p><details className="rounded-xl border border-outline-variant p-4"><summary className="cursor-pointer min-h-11 py-3 text-sm">Mostra {edition.calendar_cells.length} celle del calendario</summary><ol className="space-y-3 text-sm">{edition.calendar_cells.map((cell,i)=><li key={`${context}:cell:${i}`} className="border-t border-outline-variant pt-3"><p className="whitespace-pre-wrap break-words">{cell.text}</p><p className="text-xs text-text mt-2">Pagina {cell.evidence.page} · tabella {cell.evidence.table+1} · riga {cell.evidence.row+1} · colonna {cell.evidence.column+1}</p><p className="text-xs text-text break-all">Fonte: {cell.source_id}</p></li>)}</ol></details></section>}
      {!!edition.people.length && <section className="space-y-3"><h2 className="text-xl font-semibold text-balance">Persone indicate nel percorso</h2><p className="text-sm text-text">Ruoli e nominativi del percorso; non costituiscono assegnazioni ai singoli insegnamenti.</p><ul className="space-y-3 text-sm">{edition.people.map((person,i)=><li key={i}>{person.name_text}<p className="text-text">{otherPersonRole(person.role)}</p></li>)}</ul></section>}
      {!!edition.documents.length && <section className="space-y-4"><h2 className="text-2xl font-semibold text-balance">Documenti ufficiali</h2><OtherDocuments documents={edition.documents} year={year} /></section>}
      {!!(program.faculty_board_evidence?.length || program.faculty_directory_evidence?.length) && <section className="space-y-3"><h2 className="text-xl font-semibold text-balance">Collegio e directory dei docenti</h2><p className="text-sm text-text">Documentazione generale del percorso, con data di acquisizione propria; non attribuisce docenze nell’anno selezionato.</p><OtherDocuments documents={[...program.faculty_board_evidence||[],...program.faculty_directory_evidence||[]]} year={year} /></section>}
      <section className="space-y-4"><h2 className="text-xl font-semibold text-balance">Fonti e data di verifica</h2><Evidence sources={edition.source_evidence} /></section>
    </>}
  </div></Layout>;
}
